# Generated by Django 3.0.5 on 2020-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='images',
        ),
        migrations.AddField(
            model_name='specialist',
            name='first_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='second_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
        migrations.AddField(
            model_name='specialist',
            name='third_image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
