# Generated by Django 3.0.5 on 2020-05-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200501_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='first_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='second_image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='third_image',
            field=models.CharField(max_length=1000),
        ),
    ]
